apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-platform-prod

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: prod

patches:
  - path: secret.example-patch.yaml
