iso_url                   = "file:///C:/ffmpeg/ubuntu-24.04.4-live-server-amd64.iso"
iso_checksum              = "sha256:e907d92eeec9df64163a7e454cbc8d7755e8ddc7ed42f99dbc80c40f1a138433"
vm_name                   = "k8s-data-platform-vmware"
cpus                      = 4
memory                    = 8192
disk_size                 = 51200
ssh_username              = "ubuntu"
ssh_password              = "ubuntu"
vmware_workstation_path   = "C:/Program Files (x86)/VMware/VMware Workstation"
ovftool_path_windows      = "C:/Program Files (x86)/VMware/VMware Workstation/OVFTool/ovftool.exe"
output_directory          = "C:/ffmpeg/output-k8s-data-platform-vmware"
http_directory            = "http"
headless                  = true
vmware_network            = "nat"
