apiVersion: v1
kind: Pod
metadata:
  name: w2-admin
  namespace: data-platform-dev
spec:
  nodeName: k8s-worker-2
  restartPolicy: Never
  tolerations:
    - operator: Exists
  containers:
    - name: admin
      image: docker.io/edumgt/platform-gitlab-ce:17.10.0-ce.0
      command: ["bash", "-lc", "sleep infinity"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: hostroot
          mountPath: /host
  volumes:
    - name: hostroot
      hostPath:
        path: /
