apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-config
type: Opaque
stringData:
  config.toml: |
    concurrent = 4
    check_interval = 5

    [[runners]]
      name = "platform-k8s-runner"
      url = "http://gitlab-web:8929/"
      token = "REPLACE_ME"
      executor = "kubernetes"

      [runners.kubernetes]
        namespace = "REPLACE_NAMESPACE"
        image = "harbor.local/data-platform/platform-alpine:3.20"
        helper_image = "harbor.local/data-platform/platform-gitlab-runner-helper:x86_64-v17.10.0"
        service_account = "gitlab-runner"
        poll_timeout = 600
