apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform-configmap.yaml
  - platform-secrets.yaml
  - backend.yaml
  - frontend.yaml
  - jupyter.yaml
  - mongodb.yaml
  - redis.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: data-platform
