apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  PLATFORM_TERADATA_HOST: ""
  PLATFORM_TERADATA_USER: ""
  PLATFORM_TERADATA_PASSWORD: ""
  PLATFORM_CONTROL_PLANE_USERNAME: platform-admin
  PLATFORM_CONTROL_PLANE_PASSWORD: controlplane123!
  PLATFORM_CONTROL_PLANE_SESSION_SECRET: controlplane-session
  PLATFORM_HARBOR_USER: CHANGE_ME
  PLATFORM_HARBOR_PASSWORD: CHANGE_ME
  JUPYTER_TOKEN: CHANGE_ME
  AIRFLOW_ADMIN_USERNAME: CHANGE_ME
  AIRFLOW_ADMIN_PASSWORD: CHANGE_ME
  GITLAB_ROOT_PASSWORD: CHANGE_ME
  PLATFORM_NEXUS_ADMIN_PASSWORD: nexus123!
