apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-platform-offline

resources:
  - namespace.yaml
  - ../base
  - platform-suite.yaml

patchesStrategicMerge:
  - platform-configmap-patch.yaml
  - jupyter-patch.yaml
  - nexus-patch.yaml
  - remove-backend.yaml
  - remove-frontend.yaml
  - remove-airflow.yaml
  - remove-gitlab.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: data-platform
      app.kubernetes.io/component: offline-suite
