apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  PLATFORM_ENV: offline-suite
  PLATFORM_BACKEND_URL: http://localhost:31081/docs
  PLATFORM_FRONTEND_URL: http://localhost:31080
  PLATFORM_CONTROL_PLANE_URL: http://localhost:31080/#control-plane
  PLATFORM_AIRFLOW_URL: ""
  PLATFORM_JUPYTER_URL: http://localhost:31088/lab
  PLATFORM_NEXUS_URL: http://localhost:31091
  PLATFORM_PYPI_INDEX_URL: http://localhost:31091/repository/pypi-all/simple
  PLATFORM_NPM_REGISTRY: http://localhost:31091/repository/npm-all/
