apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-web
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
$patch: delete
