apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  PLATFORM_ENV: dev
  PLATFORM_MONGO_URL: mongodb://mongodb:27017/platform_dev
  PLATFORM_REDIS_URL: redis://redis:6379/0
  PLATFORM_BACKEND_URL: http://localhost:30081/docs
  PLATFORM_FRONTEND_URL: http://localhost:30080
  PLATFORM_CONTROL_PLANE_URL: http://localhost:30080/#control-plane
  PLATFORM_ADMIN_URL: http://localhost:30080/#sandbox-admin
  PLATFORM_AIRFLOW_URL: http://localhost:30090
  PLATFORM_JUPYTER_URL: http://localhost:30088/lab
  PLATFORM_GITLAB_URL: http://localhost:30089
  PLATFORM_HARBOR_URL: http://harbor.local:30083
  PLATFORM_HARBOR_REGISTRY: harbor.local
  PLATFORM_HARBOR_PROJECT: data-platform
  PLATFORM_HARBOR_INSECURE_REGISTRY: "true"
  PLATFORM_NOTEBOOKS_PATH: /workspace/notebooks/shared
  PLATFORM_JUPYTER_IMAGE: harbor.local/data-platform/k8s-data-platform-jupyter:latest
  PLATFORM_JUPYTER_WORKSPACE_PVC: jupyter-workspace
  PLATFORM_JUPYTER_WORKSPACE_ROOT: /workspace/user-home
  PLATFORM_JUPYTER_BOOTSTRAP_DIR: /opt/platform/bootstrap-workspace
  PLATFORM_JUPYTER_SNAPSHOT_BUILDER_IMAGE: harbor.local/data-platform/platform-kaniko-executor:v1.23.2-debug
  PLATFORM_TERADATA_DATABASE: dbc
  PLATFORM_TERADATA_FAKE_MODE: "true"
