apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  PLATFORM_TERADATA_HOST: ""
  PLATFORM_TERADATA_USER: ""
  PLATFORM_TERADATA_PASSWORD: ""
  PLATFORM_CONTROL_PLANE_USERNAME: platform-admin
  PLATFORM_CONTROL_PLANE_PASSWORD: controlplane123!
  PLATFORM_CONTROL_PLANE_SESSION_SECRET: dev-control-plane-session
  JUPYTER_TOKEN: platform123
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: admin12345!
  GITLAB_ROOT_PASSWORD: v7Q#2mL!9xC@4pR%8tZ
