apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  PLATFORM_ENV: dev
  PLATFORM_BACKEND_URL: http://dev-api.platform.local/docs
  PLATFORM_FRONTEND_URL: http://dev.platform.local
  PLATFORM_JUPYTER_URL: http://jupyter.platform.local/lab
  PLATFORM_JUPYTER_IMAGE: harbor.local/data-platform/k8s-data-platform-jupyter:latest
  PLATFORM_JUPYTER_WORKSPACE_PVC: jupyter-workspace
  PLATFORM_JUPYTER_WORKSPACE_ROOT: /workspace/user-home
  PLATFORM_JUPYTER_BOOTSTRAP_DIR: /opt/platform/bootstrap-workspace
  PLATFORM_JUPYTER_SNAPSHOT_BUILDER_IMAGE: harbor.local/data-platform/platform-kaniko-executor:v1.23.2-debug
  PLATFORM_NOTEBOOKS_PATH: /workspace/notebooks/shared
  PLATFORM_HARBOR_URL: http://harbor.local:30083
  PLATFORM_HARBOR_REGISTRY: harbor.local
  PLATFORM_HARBOR_PROJECT: data-platform
  PLATFORM_HARBOR_INSECURE_REGISTRY: "true"
  PLATFORM_TERADATA_DATABASE: dbc
  PLATFORM_TERADATA_FAKE_MODE: "true"
