#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVIRONMENT="dev"
NAMESPACE=""
BACKUP_DIR=""
ARCHIVE_PATH=""
SKIP_APPLY=0

usage() {
  cat <<'EOF'
Usage: bash scripts/restore_platform.sh [options]

Options:
  --env <dev|prod>        Target environment. Defaults to dev.
  --namespace <name>      Override namespace (default: data-platform-<env>).
  --backup-dir <path>     Backup directory generated by backup_platform.sh.
  --archive <path>        Backup archive (*.tar.gz) generated by backup_platform.sh.
  --skip-apply            Skip apply_k8s.sh execution and only try data restore.
  -h, --help              Show this help.
EOF
}

die() {
  printf '%s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

run_kubectl() {
  if [[ -z "${KUBECONFIG:-}" && -f /etc/kubernetes/admin.conf ]]; then
    env KUBECONFIG=/etc/kubernetes/admin.conf kubectl "$@"
    return
  fi
  kubectl "$@"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      [[ $# -ge 2 ]] || die "--env requires a value"
      ENVIRONMENT="$2"
      shift 2
      ;;
    --namespace)
      [[ $# -ge 2 ]] || die "--namespace requires a value"
      NAMESPACE="$2"
      shift 2
      ;;
    --backup-dir)
      [[ $# -ge 2 ]] || die "--backup-dir requires a value"
      BACKUP_DIR="$2"
      shift 2
      ;;
    --archive)
      [[ $# -ge 2 ]] || die "--archive requires a value"
      ARCHIVE_PATH="$2"
      shift 2
      ;;
    --skip-apply)
      SKIP_APPLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

case "${ENVIRONMENT}" in
  dev|prod) ;;
  *) die "Unsupported environment: ${ENVIRONMENT}" ;;
esac

if [[ -z "${NAMESPACE}" ]]; then
  NAMESPACE="data-platform-${ENVIRONMENT}"
fi

if [[ -n "${BACKUP_DIR}" && -n "${ARCHIVE_PATH}" ]]; then
  die "Use only one of --backup-dir or --archive"
fi

if [[ -z "${BACKUP_DIR}" && -z "${ARCHIVE_PATH}" ]]; then
  die "One of --backup-dir or --archive is required"
fi

require_command kubectl
require_command bash
require_command mktemp
require_command tar

TMP_DIR=""
cleanup() {
  if [[ -n "${TMP_DIR}" && -d "${TMP_DIR}" ]]; then
    rm -rf "${TMP_DIR}"
  fi
}
trap cleanup EXIT

if [[ -n "${ARCHIVE_PATH}" ]]; then
  [[ -f "${ARCHIVE_PATH}" ]] || die "Archive not found: ${ARCHIVE_PATH}"
  TMP_DIR="$(mktemp -d)"
  tar -xzf "${ARCHIVE_PATH}" -C "${TMP_DIR}"
  extracted_dir="$(find "${TMP_DIR}" -mindepth 1 -maxdepth 1 -type d | head -n 1)"
  [[ -n "${extracted_dir}" ]] || die "No backup directory found inside archive: ${ARCHIVE_PATH}"
  BACKUP_DIR="${extracted_dir}"
fi

[[ -d "${BACKUP_DIR}" ]] || die "Backup directory not found: ${BACKUP_DIR}"

if [[ "${SKIP_APPLY}" != "1" ]]; then
  bash "${ROOT_DIR}/scripts/apply_k8s.sh" --env "${ENVIRONMENT}"
fi

if [[ -f "${BACKUP_DIR}/mongo.archive.gz" ]]; then
  run_kubectl wait --for=condition=Ready pod -n "${NAMESPACE}" -l app.kubernetes.io/name=mongodb --timeout=300s
  mongo_pod="$(run_kubectl get pod -n "${NAMESPACE}" -l app.kubernetes.io/name=mongodb -o jsonpath='{.items[0].metadata.name}')"
  if run_kubectl exec -n "${NAMESPACE}" "${mongo_pod}" -- bash -lc 'command -v mongorestore >/dev/null 2>&1'; then
    cat "${BACKUP_DIR}/mongo.archive.gz" | run_kubectl exec -i -n "${NAMESPACE}" "${mongo_pod}" -- bash -lc 'mongorestore --archive --gzip --drop'
  else
    printf 'mongorestore not found in mongodb pod; skipping mongo data restore\n' >&2
  fi
else
  printf 'mongo.archive.gz not found in backup; skipping mongo data restore\n' >&2
fi

run_kubectl get pods -n "${NAMESPACE}"

