apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  PLATFORM_TERADATA_HOST: ""
  PLATFORM_TERADATA_USER: ""
  PLATFORM_TERADATA_PASSWORD: ""
  PLATFORM_CONTROL_PLANE_USERNAME: platform-admin
  PLATFORM_CONTROL_PLANE_PASSWORD: prod-controlplane-9Q4mLp!7
  PLATFORM_CONTROL_PLANE_SESSION_SECRET: prod-control-plane-session
  JUPYTER_TOKEN: prod-2v8QmL9r4XpT
  AIRFLOW_ADMIN_USERNAME: prodadmin
  AIRFLOW_ADMIN_PASSWORD: 7tM@4pL!9xQa2rVz
  GITLAB_ROOT_PASSWORD: 9xQ#4mL!7pR@2tVz
